### ISSUE TITLE
No implemenation of timing instructions

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/interpret#8]
@lsk567, I cannot see any macros or similar implementing the timing instructions of FlexPRET. Do you know where they are, and why it was removed? I am thinking on wait until and interrupt expire. I think for now I only need wait until/

**Comment by lsk567** [comment]
Sorry, I missed the notification of this issue until you closed it just now...

**Comment by erlingrj** [comment]
No problem, we had the discussion on Zulip  instead
